[project]
name = "cfasuite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastapi[standard]>=0.116.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "pypdf2>=3.0.1",
    "uvicorn>=0.35.0",
]
